### ISSUE TITLE
兄弟 请教个问题SmartyException thrown with message "Unable to load template file 'user/index.tpl'"  

### ISSUE THREAD

**Issue by mingsire** [xiecuyu/sspanel-v3-mod-mod#1]
SmartyException thrown with message "Unable to load template file 'user/index.tpl'"

问题描述：
只要登录成功以后浏览器存在cookie就会显示无限重定向请清除cookie。

这个该是什么原因造成的？求指引。谢谢啊。。

**Comment by xiecuyu** [comment]
貌似是因为浏览器内核问题，我这儿都是在安卓chrome上出现的，但是有人告诉我他们换用数据流量可以跳过这个问题。。。不太清楚，可能和核心代码有关
